/// Flutter icons MyIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData eh = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jm = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ehFolder = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jmFolder = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
